/* generated by dia/codegen.py */
/*(NULL)*/
class Gato : Mamifero 
{
};

/*(NULL)*/
class Class : Cachorro, Cachorro, Gato, Gato 
{
};

/*(NULL)*/
class Mamifero 
{
};

/*(NULL)*/
class Cachorro : Mamifero 
{
public:
	String latir ();
private:
	int Qnt_patas;
	int Qnt_rabos;
};

